### ISSUE TITLE
XML checkouts are slow. Is it worth shallow cloning?

### ISSUE THREAD

**Issue by andrew-c-ross** [NOAA-GFDL/CEFI-regional-MOM6#28]
Edit: going to close this because I misread the time command output.

**Comment by yichengt900** [comment]
@andrew-c-ross, jsut let you know that there are also some ongoing discussions in GHAG regarding the performance issues of Gaea f5. We've noticed that the compiling time as well as the time of data transfer are extremely unstable and need to be addressed. Just for your information

**Comment by andrew-c-ross** [comment]
Sounds good. I've definitely noticed the long transfer times from Gaea to GFDL. Mentioned this to Dennis yesterday since I didn't know if it was a local or remote issue.
