### ISSUE TITLE
Compilation error: Fails on Centos, Format specifier error

### ISSUE THREAD

**Issue by Parag0206** [NOAA-GFDL/CEFI-regional-MOM6#38]
Hi,

I am trying to compile the MOM6+SIS2+COBALTv2 coupled model on CentOS. I am using "triton-gnu.mk" file(the error repeats for linux-ubuntu-xenial-gnu,mk file too). I get the following error:
```
/home/MOM6/CEFI-regional-MOM6/builds/../src/ocean_BGC/generic_tracers/generic_tracer_utils.F90:610:29:

  610 |         write(var_string, '(e0.16)') var
      |                             1
Error: Positive width required in format specifier E at (1)
```
Can be rectified. The mkmf file speficies the following flags:

````
-fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check
````

Can you help me here?

**Comment by yichengt900** [comment]
Hi @Parag0206,

Thanks for opening this issue. Could you please provide a bit more detail about your machine configuration, such as your CentOS version and your Fortran compiler? This information will help me try to reproduce your error on my end. In the meantime, you could try modifying that specific line as follows:

```console
write(var_string, '(E20.16)') var
```

to see if it resolves your problem.

**Comment by Parag0206** [comment]
Hi, @yichengt900 

Thanks for your reply.
My system specifications are as follows:
```
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
Also, The fix you suggested works. I had to change that line of code and the compilation proceeds.
Thanks for this.
