### ISSUE TITLE
Coupler error; Fortran runtime error; atm%pelist

### ISSUE THREAD

**Issue by Parag0206** [NOAA-GFDL/CEFI-regional-MOM6#41]
Hi,

I am trying to run MOM6+COBALTv2 coupled on a CentOS system. While running a case, I am getting the following error:
```
At line 1466 of file /home/mom6/CEFI-regional-MOM6/builds/../src/coupler/full//coupler_main.F90
Fortran runtime error: Index '1' of dimension 1 of array 'atm%pelist' above upper bound of 0
```

The coupler fails I guess.The  &coupler_nml in input,nml looks like this
```
 &atmos_model_nml
        layout= 1,1
/

 &coupler_nml
        months = 0
        days   = 182
        current_date = 2013,4,1,0,0,0
        hours = 0
        minutes = 0
        seconds = 0
        calendar = 'NOLEAP'
        dt_cpld  = 3600
        dt_atmos = 3600
        do_atmos = .false.
        do_land = .false.
        do_ice = .true.
        do_ocean = .true.
        atmos_npes = 0,
        ocean_npes = 0,
        concurrent = .false. 
        use_lag_fluxes=.false.
        atmos_nthreads = 1
        ocean_nthreads = 1
        do_chksum = .false.
        do_endpoint_chksum = .false.
/

 &diag_manager_nml
        max_files = 600 
        flush_nc_files=.false.
        max_axes = 600
        max_num_axis_sets = 600
        max_input_fields = 2000 
        max_output_fields = 5000 
        mix_snapshot_average_fields=.false.
/

 &fms_io_nml
        fms_netcdf_restart=.true. 
        threading_read='multi'
        max_files_r = 800
        max_files_w = 800
        checksum_required=.false.
/

 &fms_nml
        clock_grain='ROUTINE' 
        clock_flags='NONE'
        domains_stack_size = 8000000
        stack_size =0
/

```

Can anyone help me with this?

**Comment by yichengt900** [comment]
@Parag0206 , thanks for raising this issue. Your `coupler_nml` looks ok to me. In order to investigate the issue further, would you mind to share your model configurations (e.g., grid files, model setup files) so I can attempt to replicate the error on my end? Additionally, could you provide details on how you compile your model and which source codes (GitHub repo, tag, etc.) you are using? This information will help me determine the root cause. Thanks.

**Comment by yichengt900** [comment]
@Parag0206 Thanks. One quick question: are you building your model with `-t repro` when using the build script `linux-build.bash`? If so, try removing `-fbounds-check` on line 31 in your `triton-gnu.txt` and re-building the model to see if it solves your problem.

**Comment by Parag0206** [comment]
Hi @yichengt900, Thanks. 
The fix you suggested, of removing "-fbounds-check" in .mk file, does lead to elimination of that error. 

But, I am now seeing a new error:
```
Error termination. Backtrace:
Operating system error: Cannot allocate memory
Allocation would exceed memory limit
```
Can you help me resolve this?

**Comment by yichengt900** [comment]
Hi @Parag0206, hmm, that's interesting. It's hard for me to debug without actually running your experiment. Could you share the grid files, at least? I can then try to reproduce your issue on my end.

**Comment by Parag0206** [comment]
Hi @yichengt900, I have shared the grid files and parameter files here:
https://github.com/Parag0206/BOB_0.073_2013 

Thanks for your help. Do let me know if you require any other files
