### ISSUE TITLE
ftp link

### ISSUE THREAD

**Issue by eric-mortenson** [NOAA-GFDL/CEFI-regional-MOM6#47]
Hello, I tried to access the link for the NWA12 datasets in exps directory (ftp.gfdl.noaa.gov:/pub/Yi-cheng.Teng/nwa12_datasets.tar.gz) but couldn't. I get an error message saying "No such file or directory".

**Comment by yichengt900** [comment]
Hi @eric-mortenson,
It looks like the file you are looking for was removed, likely because it hasn't been accessed in a while and was automatically deleted by the system. I am re-uploading it now and will let you know once it's done.

**Comment by yichengt900** [comment]
Hi @eric-mortenson , now the `nwa12_datasets.tar.gz` has been re-uploaded. Enjoy!
