### ISSUE TITLE
Missing single column initial condition files

### ISSUE THREAD

**Issue by andrew-c-ross** [NOAA-GFDL/CEFI-regional-MOM6#71]
The OM4.single_column.COBALT experiment references two initial condition files that are not included in the link referenced in the README (ftp.gfdl.noaa.gov:/pub/Yi-cheng.Teng/nwa12_datasets.tar.gz).

MOM_IC.nc, for example
https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/23d647fa0285ed0bd09e184ff2317be10331be58/exps/OM4.single_column.COBALT/MOM_override#L13-L14

bgc_woa_esper_ics_1993_2023-04_BATS.nc, for example
https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/23d647fa0285ed0bd09e184ff2317be10331be58/exps/OM4.single_column.COBALT/field_table#L29

It's not clear to me whether the second gets used since it also specifies: https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/23d647fa0285ed0bd09e184ff2317be10331be58/exps/OM4.single_column.COBALT/MOM_override#L40

`bgc_woa_esper_ics_1993_2023-04_BATS.nc` is available in the world-shared datasets on Gaea, but `MOM_IC.nc` is not as far as I can tell.

I may be forgetting something obvious, though, because I've acquired both of these files from somewhere sometime in the recent past.

**Comment by yichengt900** [comment]
Hi @andrew-c-ross , good catch.The 1D dataset can be downloaded from the FTP link provided here:
https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/23d647fa0285ed0bd09e184ff2317be10331be58/.github/workflows/mom6_cobalt_1D.yaml#L37

This dataset includes both the NetCDF files you're looking for. I will update the README and the online documentation accordingly.
