### ISSUE TITLE
Diagnostic scripts producing inconsistent output

### ISSUE THREAD

**Issue by uwagura** [NOAA-GFDL/CEFI-regional-MOM6#87]
Several scripts within the `diagnostics/physics` subfolder have been producing output that is inconsistent between runs. When I originally ran `sss_eval.py` on 07/29/2024, I produced the following figure:

![sss_eval](https://github.com/user-attachments/assets/c4755df0-7437-4a49-99c4-7bf2a0a3d064)

However, all recent runs (i.e from at least 08/29/2024 to present) produce the following output: 

![sss_eval_config](https://github.com/user-attachments/assets/6cd99171-d3b0-4ff8-9ba8-25166a120b38)

Note that the skill metrics are slightly different, and that the `model - oisst`,`model -glorys`, and `model` plots are all slightly different between these two runs.

Andrew previously ran the same script, which was published [here](https://gmd.copernicus.org/articles/16/6943/2023/gmd-16-6943-2023-discussion.html), and produced a figure with a slightly different `glorys` plot and slightly different skill metrics for 
`model-glorys` compared to both of the above runs

![figure04](https://github.com/user-attachments/assets/f25dc0e3-e038-4618-bb34-c2bffa9998c2)

A similar issue occurs with the `sst_eval` script. A run that took place around 07/29/2024 produced the following output: 

![sst_eval](https://github.com/user-attachments/assets/2e14621d-b6d9-4bed-99f5-22b4922d205c)

while a run from a few days later ( 08/01/2024 ) produced the following figure: 
![sst_eval](https://github.com/user-attachments/assets/69530d04-2a4b-43db-9ba7-893bc614b2c5)

The august runs of these plots were likely produced using Yi-Cheng's `setup` conda environment, which hasn't been modified recently. The july runs *most* likely used the same environment as well. Likewise, all of these runs used the same history files (currently listed at the top of each of these scripts), and these files have not been altered since the initial run. 

It's unclear what's causing the discrepency. MSD thinks the analysis nodes having slightly different firmware ( some nodes use [avx](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) , while others don't ) may have contributed to this issue, or perhaps some other subtle hardware difference that python doesn't like. In my testing, I did not notice any difference between the nodes with different versions of `avx` ( listed [here](https://wiki.gfdl.noaa.gov/index.php/Post-processing_and_Analysis_User_Guide#cite_note-arch-4)). 

Regardless, if you run the diagnostic scripts and receive two different plots, please respond with 1.) the path to the python environment where you ran the script and 2.) The analysis node you ran the script on so that we can look into both hardware and software issues when debugging this.

**Comment by andrew-c-ross** [comment]
It's interesting that in both cases, the more recent version of the plots is closer to what is in the original published paper. This would suggest there was something weird in July that has been fixed, rather than a problem that started in August.

**Comment by uwagura** [comment]
@andrew-c-ross , Yeah, it does seem like the results from July were the anomaly across most of the plots. The only exception I see so far is the mld003 plot.  It's possible that I ran those figures in some strange python environment that I've since deleted, containing packages that have since been updated. It's still weird though that the plots from paper are still *slightly* different from the plots from right now.

mean_ssh_eval 07/29/2024
![mean_ssh_eval](https://github.com/user-attachments/assets/815ce715-2595-4caa-ade3-b87fba476380)

mean_ssh_eval 09/12/2024
![mean_ssh_eval](https://github.com/user-attachments/assets/dbda3f91-d498-4a59-8ddc-6cdb7dc47b61)

sst_trends 07/29/2024:
![sst_trends](https://github.com/user-attachments/assets/8d91e203-3199-4e5a-bef1-c2f55b7a6127)

sst_trends 09/12/2024:
![sst_trends](https://github.com/user-attachments/assets/a818521a-6648-429d-bd89-6e1fff926dc9)

mld003_eval 07/29/2024
![mld003_eval](https://github.com/user-attachments/assets/7e301a5d-12fb-4af4-8139-d111ad08ea07)

mld003_eval 09/12/2024
![mld003_eval](https://github.com/user-attachments/assets/b53f779a-4c0c-4381-87bd-8e56de904ad2)

**Comment by uwagura** [comment]
Turns out I was mistaken: All of the July plots shown in this issue were actually produced with history data stored in my own archive, which was only available for about 10 years, and not the 27 year history data from the paper that produced all of the August plots. I guess opening and investigation this issue was nothing more than a lesson in tracking how I produce plots a bit more carefully. 

As for the discrepancy between the plots from the paper and the August plots: It looks like the plots published in the paper only used glorys data from 1993-2019, while the glorys data in `/work/acr/mom6/diagnostics/glorys/glorys_sfc.nc` stretches from 1993 to 2023-05. I can reproduce the plots in the paper by cutting off the glorys dataset in 2019, so this was also just a dataset issue. 

All told, this issue is completely resolved.
